name: Maximize Runner Space

on:
  push:
    branches: [ maximize_github_runner_space ]
  # schedule:
  #   - cron: '0 16 * * *'  # 每天北京时间 00:00（UTC 16:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Beijing Timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Check disk space
      run: |
        df -h
        pwd
        du -sh ./
        # du -h -d 2 /
    
    # 详见：https://github.com/marketplace/actions/maximize-github-runner-space
    - name: Maximize Runner Space
      uses: justinthelaw/maximize-github-runner-space@main
      with:
        cleanup-profile: custom
        # remove-dotnet: "true"         # Removes .NET runtime and libraries. (frees ~2 GB)
        # remove-android: "true"        # Removes Android SDKs and Tools. (frees ~9 GB)
        # remove-haskell: "true"        # Removes GHC (Haskell) artifacts. (frees ~5 GB)
        # remove-codeql: "true"         # Removes CodeQL Action Bundles. (frees ~5 GB)
        # remove-docker-images: "true"  # Removes cached Docker images. (frees ~3 GB)
        # Custom removal actions
        # remove-large-packages: "true" # Removes unwanted large Apt packages. (frees ~3 GB)
        # remove-cached-tools: "true"   # Removes cached tools used by setup actions by GitHub. (frees ~8 GB)
        remove-swapfile: "true"       # Removes the Swapfile. (frees ~4 GB)
    
    - name: Check disk space
      run: |
        df -h
        pwd
        du -sh ./
    