name: Maximize Runner Space

on:
  push:
    branches: [ maximize_github_runner_space ]
  # schedule:
  #   - cron: '0 16 * * *'  # 每天北京时间 00:00（UTC 16:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Beijing Timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Check disk space
      run: |
        df -h
        pwd
        du -sh ./
        